@baseurl = http://localhost:3333
@authToken = {{authenticate_user.response.body.access_token}}

# @name create_account
POST {{baseurl}}/accounts
Content-Type: application/json

{
    "name": "Kayo Vinicius",
    "email": "kayo@teste.com",
    "password": "teste123"
}


###
# @name authenticate_user
POST {{baseurl}}/sessions
Content-Type: application/json

{
   "email": "kayo@teste.com",
   "password": "123456"
}

###
# @name create_question
POST {{baseurl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   "title": "tomara que de",
   "content": "testando codigo"
}

###
# @name fetch_recent_question
GET {{baseurl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   
}